# Generated by Django 4.0.4 on 2022-04-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cheese')),
            ],
        ),
    ]
