# Generated by Django 3.1.2 on 2020-11-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country_of_origin', models.CharField(max_length=200)),
                ('fat_content', models.FloatField(null=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'last_updated',
            },
        ),
    ]
