# Generated by Django 3.1.2 on 2020-11-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheese",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
