# Generated by Django 4.0.4 on 2022-04-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('country_of_origin', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('fat_content', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'last_updated',
            },
        ),
    ]
